RateIt/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #users actions

  get 'home', to: 'users#home'

  get 'signup', to: 'users#signup'
  post '/signup', to: 'users#new_sign_up'

  get 'login', to: 'users#login'
  post '/login', to: 'users#create'
  post '/login', to: 'sessions#create'
  
  get '/users/:id', to: 'users#show', as: 'user'
  get '/logout', to: 'users#logout'

  get '/auth/google_oauth2/callback', to: 'sessions#create'


   # implement resources but get an understanding first.
      #Vehicle action
   resources :vehicles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :ratings, only: [:new, :create, :index, :destroy]
   end

   #Vehicle Ratings
   resources :ratings, only: [:new, :index, :create]
end

RateIt/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

RateIt/app/models/categories.rb
class Categories < ApplicationRecord

end

RateIt/app/models/rating.rb
class Rating < ApplicationRecord

  belongs_to :user
  belongs_to :vehicle

  validates :user, uniqueness: { scope: :vehicle, message:"this vehicle has been already been rated"}
  
  validates :vehicle_ratings, presence: true


end

RateIt/app/models/user.rb
class User < ApplicationRecord

    has_many :vehicles  # those were the vehicles created
    has_many :ratings
   # has_many :vehicles, through: :ratings


	has_secure_password

    validates :username, :email, uniqueness: true
    validates(:password, { :length => { :in => 4..166 } })
    validates :username, :email, presence: true

end

RateIt/app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :vehicle_type, presence: true
  validates :year,  presence: true, length: {minimum: 4}
  validates :make,  presence: true
  validates :model,  presence: true
  validates :style,  presence: true
  

  has_many :ratings
  has_many :users, through: :ratings
  belongs_to :user
end

RateIt/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include ApplicationHelper
end

RateIt/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    
    def new
      @rating = Rating.new
      @rating.build_vehicle
      if params[:vehicle_id] && @vehicle = Vehicle.find_by_id(params[:vehicle_id])
        @rating = @vehicle.ratings.build
      else
        @rating = Rating.new
        @rating.build_vehicle
      end
    end

    def index
      if  params[:vehicle_id] && @vehicle = Vehicle.find_by_id(params[:vehicle_id])
       @ratings = @vehicle.ratings
      else
        @ratings = Rating.all
      end
    end

    def show
      @rating = current_user.ratings
    end

    def create
       @rating = current_user.ratings.create(rating_params)
      if @rating.save
       redirect_to  '/vehicles'
      else
        render :new
      end
    end

    def update
      @rating = Rating.find(params[:id])
      
    end

    def edit
    #  @ = .find(params[:id])
    end
    
    def destroy
    #   = .find(params[:id])
    end

    private

    def rating_params
      params.require(:rating).permit(:vehicle_ratings, :vehicle_id)
    end
end

RateIt/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    protect_from_forgery

  def new
  end

  def create #Logged user in redirected to user page
    auth_hash = request.env["omniauth.auth"]
      # They logged into oauth
    oauth_email = request.env["omniauth.auth"]["info"]["email"]
      if @user = User.find_by(:email => oauth_email)
       #raise "existing user".inspect
       session[:user_id] = @user.id
       redirect_to user_path(@user.id)
      else
       user = User.new(:email => oauth_email, :password => SecureRandom.hex, :username => oauth_email)
      if user.save
       session[:user_id] = user.id
       redirect_to user_path(@user.id)

      end
    end
  end


  def destroy
    reset_session
    redirect_to login_path
  end

  private
  def auth
    request.env['omniauth.auth']
  end
end

RateIt/app/controllers/users_controller.rb
class UsersController < ApplicationController
    protect_from_forgery
  

    def user   #homepage
      render "/home"
    end

    def new_sign_up  # creating users
      @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user.id)
        else
          redirect_to '/login'
        end
    end
     def login  # logging user in
      #redirect_to '/login'
     end

    def create  #normal login with username and password
     @user = User.find_by(username: params[:user][:username])
     if @user.try(:authenticate, params[:user][:password])
       session[:user_id] = @user.id
       redirect_to user_path(@user.id)
      else
       redirect_to '/login'
      end
    end

    def show
      @vehicle = current_user.vehicles
    end

    def logout  #signing a user out
      session.delete :user_id
      redirect_to "/home"
    end


    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

RateIt/app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

   def new
      @vehicle = Vehicle.new
   end

   def edit
    @vehicle = Vehicle.find(params[:id])
   end

   def update
   @vehicle = Vehicle.find(params[:id])
      if @vehicle.update(model: params[:vehicle][:model], make: params[:vehicle][:make], year: params[:vehicle][:year], style: params[:vehicle][:style],  vehicle_type: params[:vehicle][:vehicle_type])
       redirect_to vehicle_path(@vehicle)
      else
        render :edit
      end
   end

   def create
         @vehicle = Vehicle.create(vehicle_params)
      if  @vehicle.save

         redirect_to '/vehicles'
      else
         @vehicle = Vehicle.find_by_id(params[:vehicle_id]) if params[:vehicle_id]
         render :new
      end
   end

   def index
      @vehicles = Vehicle.all
   end

   def show
      @vehicle = Vehicle.find(params[:id])
   end


   def destroy
      @vehicle = Vehicle.find(params[:id])
      @vehicle.destroy
      redirect_to '/vehicles'
   end


   private

   def vehicle_params
    params.require(:vehicle).permit(:vehicle_type, :style, :model, :make, :year, :user_id)
   end
end

RateIt/app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
      !!session[:user_id]
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if !!session[:user_id]
    end
end

RateIt/app/helpers/sessions_helper.rb
module SessionsHelper
end

RateIt/app/helpers/users_helper.rb
module UsersHelper
end

RateIt/app/helpers/vehicles_helper.rb
module VehiclesHelper
end

RateIt/app/views/Ratings/index.html.erb
<h1> List of Vehicle Ratings <br>   </h1>


<% @ratings.each do |r| %>

 User: <%= r.user_id%>.Vehicle Id: <%= r.vehicle_id%>,
 Vehicle Name:  <%= r.vehicle.make%>,  Vehicle Model:  <%= r.vehicle.model %> ,  Vehicle Rating: <%= r.vehicle_ratings %><br><br>

<%end%>

<%= link_to "Logout", logout_path %> <%= link_to 'Back', '/users/:ids' %>

RateIt/app/views/Ratings/new.html.erb
  <h2>Current Vehicle to Rate</h2>

  
<% if @rating.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @rating.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  
 <%= form_for @rating do |r| %>
  <label> Vehicle Rating </label>
  <%= r.text_field :vehicle_ratings %> 
  <%= r.hidden_field :vehicle_id, :value => @rating.vehicle.id %>

  <%= r.submit "Submit" %>

 <%end%><br>

<%= link_to "Logout", logout_path %> <%= link_to 'Back', '/users/:id' %>

RateIt/app/views/Ratings/show.html.erb
<h1>Viewing Your Ratings</h1> 

<% current_user.vehicles.each do  |v|%>
 Vehicle Type:<%= v.vehicle_type %><br>
 Vehicle year:<%= v.year %><br>
 Vehicle Make:<%= v.make %><br>
 Vehicle Model:<%= v.model %><br>
 Vehcile Style:<%= v.style%><br>   
<%end%><br>

<% current_user.ratings.each do |r|%>
 Vehicle Rating:<%= r.vehicle_ratings %>
<%end%><br>
  

<%= link_to "Logout", logout_path %>  <%= link_to 'Back', '/users/show' %>

RateIt/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rateit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
  <div>
  <% if logged_in? %>
  <h1> Hello Welcome to RateIt User: <%= current_user.username  %>  </h1>
  <% end %>
  </div>
    <%= yield %>
  </body>
</html>

RateIt/app/views/users/edit.html.erb
<h1> edit page</h1>


<%= link_to 'Back', vehicles_path %>

RateIt/app/views/users/home.html.erb
<center><h1>Welcome to RateIt</h1></center>

<center><a href="/signup">Sign Up</a>--<a href="login">Log In</a></center>

(JH).&copy;

RateIt/app/views/users/login.html.erb
<center><h1>Login to your Account</h1>




<%= form_for(:user, url: login_path) do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username, class: "shortInput" %> <br />
  <%= f.label :password %>
  <%= f.password_field :password, class: "shortInput" %><br><br>

 <%= f.submit "login", class: "button login" %>   
<% end %> 



 <% if session[:user_id] %>
  <h1><%= @user.name %></h1>
  <h2>Email: <%= @user.email %></h2>
  <h2>Google UID: <%= @user.uid %></h2>
  
  <% else %>
    <%= link_to('Log in with google!', '/auth/google_oauth2') %>
  <% end %>
  

<br></center>
(JH).&copy;

RateIt/app/views/users/show.html.erb
<h2>Choose a Category</h2>

<%= link_to "Automobiles", new_vehicle_url %><br>

<%= link_to "Users Vehicles", '/vehicles' %><br>



<%= link_to "Logout", logout_path %>

RateIt/app/views/users/signup.html.erb
<h1>Sign_up For new Account</h1>


<%= form_for :user, class: "new_sign_up" do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username, class: "shortInput" %> <br />

  <%= f.label :email, "Email Address" %>
  <%= f.text_field :email, class: "shortInput" %> <br />

  <%= f.label :password %>
  <%= f.password_field :password, class: "shortInput" %> <br />

  <%= f.submit "Create account", class: "button createAccount" %>

<% end %>

RateIt/app/views/vehicles/edit.html.erb
<h1>Edit A Vehicle</h1>
  

<% if @vehicle.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @vehicle.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= form_for @vehicle do |r| %>
    <label>Vehicle Type :</label><br>
    <%= r.text_field :vehicle_type %><br>

    <label>Vehicle Make: </label><br>
    <%= r.text_field :make %><br>
   
    <label>Vehicle Model: </label><br>
    <%= r.text_area :model %><br>

    <label>Vehicle Year: </label><br>
    <%= r.text_area :year %><br>

    <label>Vehicle Style: </label><br>
    <%= r.text_area :style %><br>

    <%= r.submit "Submit Vehicle" %>
  <% end %>

 


 
 <%= link_to "Logout", logout_path %> <%= link_to 'Back', '/users/:id' %>

RateIt/app/views/vehicles/index.html.erb
<div>
<h3>Filter Vehicles:</h3>
<%= form_tag("/vehicles", method: "get") do %>
  <%= select_tag "vehicle", options_from_collection_for_select(Vehicle.all, "id","model", "make"), include_blank: true %>
  <%= submit_tag "Filter" %>
<% end %>
</div>

<% current_user.vehicles.each do |vehicle|%><br>
  Vehicle Type:  <%= vehicle.vehicle_type %><br>
  Vehicle Year:  <%= vehicle.year %><br>
  Vehicle Make:  <%= vehicle.make %><br>
  Vehicle Model: <%= vehicle.model %><br>
 

  <%= link_to "Edit Vehicle", edit_vehicle_url(vehicle.id) %>
  <%= button_to "Delete Vehicle", vehicle_path(vehicle.id), method: :delete %>
  
  <%= link_to "Rate Vehicle", new_vehicle_rating_path(vehicle.id) %>
  <%= link_to "Show Vehicle", vehicle_path(vehicle.id) %>
  
  
<%end%><br><br>
<%= link_to "Logout", logout_path %> <%= link_to 'Back', '/users/:id' %> <%= link_to "All Ratings", '/ratings' %>

RateIt/app/views/vehicles/new.html.erb
<h2> Make Your Selections Below To RateIt.</h2>


<br>Type Of Vehicle

<% if @vehicle.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

    <ul>
    <% @vehicle.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @vehicle, :url => {:action => "create"} do |f| %>
    
    <%= f.label :Car %>
    <%= f.radio_button :vehicle_type, "Car", class: "shortInput" %> <br />

    <%= f.label :Truck  %>
    <%= f.radio_button :vehicle_type, "Truck", class: "shortInput" %> <br />

    <%= f.label :Motorcycle  %>
    <%= f.radio_button :vehicle_type, "Motorcycle", class: "shortInput" %> <br />
    
    <%= f.hidden_field :user_id, value: current_user.id %>

      <br>
      Create a Vehicle<br>

    <%= f.label :Year %>
    <%= f.text_field :year %> <br />

    <%= f.label :Make  %>
    <%= f.text_field :make %> <br />

    <%= f.label :Model  %>
    <%= f.text_field :model %> <br />

    <%= f.label :Style  %>
    <%= f.text_field :style %> <br />

    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit "Submit" %>  <%= link_to "Logout", logout_path %>
   
<% end %>
 

RateIt/app/views/vehicles/show.html.erb
<div>

    Vehicle Type: <%= @vehicle.vehicle_type %><br>
    Vehicle Year: <%= @vehicle.year %><br>
    Vehicle Make: <%= @vehicle.make %><br>
    Vehicle Model: <%= @vehicle.model %><br>
    Vehicle Style: <%= @vehicle.style %><br>

    Vehicle Rating: <% @vehicle.ratings.each do |r| %>
                       <%= r.vehicle_ratings %><br>
                    <%end%>
</div>

<%= link_to "Logout", logout_path %> <%= link_to "Edit Vehicle", edit_vehicle_url %> <%= link_to 'Back', '/users/show' %><%= link_to "Ratings", vehicle_ratings_path(@vehicle.id)  %>


<